#!/usr/bin/ruby

class Inverter
	def initialize(delegate)
		@delegate = delegate
	end

	def ===(toCompare)
		! (@delegate === toCompare)
	end
end

Tabness = 8
Flatten = ARGV.delete('-f')
ToMatch = ARGV.delete('-v') ? [Inverter.new(Regexp.new(ARGV.shift))] : [Regexp.new(ARGV.shift)]

def decide_indentation(l)
	/^(?<stuff>\s*)/ =~ l
	chars = stuff.chars.group_by(&:itself)
	Tabness * (chars["\t"] || []).size + (chars[" "] || []).size
end

$context = {}
ARGF.each_line do |l|
	next if /\A\s*\Z/ === l
	indentation = decide_indentation(l)

	$context.delete_if {|ind,_| ind > indentation }
	$context[indentation] = l

	next unless ToMatch.all?{|m| m === l }

	if Flatten
		puts $context.sort.map{|ind, l| l.strip }.join(' ')
	else
		$context.sort.each do |ind, l|
			puts l
		end
		$context.delete_if {|ind,_| ind <= indentation }  # printed all this now, don't print it again
	end
end
